name: Build apk
 
on:
  pull_request: {}
  push: { branches: [release] }
 
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
 
jobs:
  build:
    name: Compile Project
    runs-on: ubuntu-latest
    steps:
        
     
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          
      
          
      - name: Cache actions
        uses: actions/cache@v2
        with:
          path: \
          key: Library-BigMiner-Android
          restore-keys: |
            Library-BigMiner-
            Library-

     
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
 
 
      # Build
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          versioning: Semantic
     
      - name: Checkout
        uses: actions/checkout@v2  
        
      - name: Git Release
        # You may pin to the exact commit or the version.
        # uses: anton-yurchenko/git-release@7a1349223bc56b846390a268b5c9948d8db70e7d
        uses: anton-yurchenko/git-release@v3.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
        with: | 
          build/*.apk
          
      # Output 
      - uses: actions/upload-artifact@v1
        with:
          name: BigMiner.apk
          #path: build
          warn: Build Acction Failed    

