name: Build apk

on:
  push:
    branches:
      - release

  workflow_dispatch:
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  TARGETPLATFORM : Android

jobs:
  showMe:
    name: Show Environment variables
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  build:
    name: Compile Project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true



      # Build
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ env.TARGETPLATFORM }}
          versioning: Semantic

      - name: Upload the artifact
        uses: actions/upload-artifact@v1
        with:
          name: Android.apk
          path: build/Android/Android.apk

  uploadApk:
    name: Upload .apk
    runs-on: ubuntu-latest
    needs: build
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        id: tag_bump
        uses: moble/github-tag-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: none

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.8
        with:
          path: ./

      - name: Display structure of downloaded files
        run: ls -R

      - name: Rename .apk files
        run: mv Android.apk/Android.apk BigMiner.${{ steps.tag_bump.outputs.tag }}.${{ github.run_number }}

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "*.apk"
          body: ${{ github.event.head_commit.message }}
          tag: apk.${{ steps.tag_bump.outputs.tag }}.${{ github.run_number }}
          name: Build ${{ steps.tag_bump.outputs.tag }}


