name: Build apk
 
on:
  push:
    branches:
      - release
      
  workflow_dispatch:
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  TARGETPLATFORM : Android
 
jobs:
  showMe: 
    name: Show Environment variables
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
        
  build:
    name: Compile Project
    runs-on: ubuntu-latest
    steps:

      - name: Bump version and push tag
        id: tag_bump
        uses: moble/github-tag-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: none
            
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ env.TARGETPLATFORM }}
          restore-keys: |
            Library-${{ env.TARGETPLATFORM }}
       
      # Build
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ env.TARGETPLATFORM }}
          versioning: Semantic     
               
      
      - name: Create a GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: apk.${{ steps.tag_bump.outputs.tag }}.${{ github.run_number }}
          release_name: Release ${{ steps.tag_bump.outputs.tag }}
          body: ${{ steps.tag_bump.outputs.changelog }}
    
      - name: Upload the artifact
        uses: actions/upload-artifact@v1
        with:
          name: Android.apk
          path: build/Android/Android.apk
          
      - name: Create GitHub release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          INPUT_CREATED_TAG: ${{ steps.create_release.id }}
          args: build/Android/Android.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  





